apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ut8hvur7q-java-springboot
  janus-idp.io/tekton: ut8hvur7q-java-springboot
  backstage.io/kubernetes-id: ut8hvur7q-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ut8hvur7q-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
